// Generated by CoffeeScript 1.3.3
(function() {
  var reboot, root;

  root = typeof window !== "undefined" && window !== null ? window : global;

  reboot = (function() {

    function reboot() {
      console.log('rebooted');
    }

    reboot.prototype.tableColumnsToObject = function(table) {
      var columns, values, _i, _len, _ref;
      columns = {
        head: [],
        values: []
      };
      columns.head = $(table).find('thead th').map(function() {
        return $(this).text().replace(/[\r\n]+/, '').trim();
      });
      _ref = columns.head;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        values = _ref[_i];
        columns.values.push([]);
      }
      $(table).find('tbody tr').map(function() {
        return $(this).find('td').each(function(index) {
          return columns.values[index].push($(this).text().replace(/[\r\n]+/, '').trim());
        });
      });
      return columns;
    };

    reboot.prototype.rebootTableBarCharts = function() {
      var that;
      that = this;
      return $('table.table-chart-bar-horizontal').each(function() {
        var columns;
        columns = that.tableColumnsToObject(this);
        return console.log(columns);
      });
    };

    return reboot;

  })();

  if (!(typeof $ !== "undefined" && $ !== null)) {
    throw 'jQuery needs to be installed and required in order to get reboot to run';
    console.error('reboot failed: jQuery not initialized');
  } else {
    $(document).ready(function() {
      var rebooter;
      rebooter = new reboot;
      return rebooter.rebootTableBarCharts();
    });
  }

}).call(this);
