// Generated by CoffeeScript 1.3.3
(function() {
  var reboot, root;

  root = typeof window !== "undefined" && window !== null ? window : global;

  reboot = (function() {

    reboot.tables = 0;

    function reboot() {
      console.log('rebooted');
    }

    reboot.prototype.tableColumnsToObject = function(table) {
      var columns, values, _i, _len, _ref;
      columns = {
        head: [],
        values: []
      };
      columns.head = $(table).find('thead th').map(function() {
        return $(this).text().replace(/[\r\n]+/, '').trim();
      });
      _ref = columns.head;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        values = _ref[_i];
        columns.values.push([]);
      }
      $(table).find('tbody tr').map(function() {
        return $(this).find('td').each(function(index) {
          return columns.values[index].push($(this).text().replace(/[\r\n]+/, '').trim());
        });
      });
      return columns;
    };

    reboot.prototype.isNumber = function(value) {
      if (void 0 === value || null === value) {
        return false;
      }
      if (typeof value === 'number') {
        return true;
      }
      return !isNaN(value - 0);
    };

    reboot.prototype.checkArrayOnlyContainsNumbers = function(array) {
      var value, _i, _len;
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        value = array[_i];
        if (!this.isNumber(value)) {
          return false;
        }
      }
      return true;
    };

    reboot.prototype.arraySum = function(array) {
      var sum, value, _i, _len;
      sum = 0;
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        value = array[_i];
        sum += value - 0;
      }
      return sum;
    };

    reboot.prototype.rebootTableBarCharts = function() {
      var makeNewIds, renderBarChart, sumColumns, that;
      that = this;
      sumColumns = function(columns) {
        var subarray, sums, _i, _len, _ref;
        sums = [];
        _ref = columns.values;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          subarray = _ref[_i];
          if (!that.checkArrayOnlyContainsNumbers(subarray)) {
            throw 'the table body contains cells that do not contain numbers';
          }
          sums.push(that.arraySum(subarray));
        }
        return sums;
      };
      makeNewIds = function(table) {
        if (!(table.id === "")) {
          return "" + table.id + "-rebooted";
        } else {
          table.id = "table-source-chart-" + reboot.tables;
          return "table-chart-bar-" + reboot.tables;
        }
      };
      renderBarChart = function(attachment, table, width, margin) {
        var chart, classPart1, classPart2, columnSums, columns, counter, endLevel, id, level, levelAddition, styleColumn, styleColumn1, styleColumn2, styleContainer, stylePart, subtable, value, _i, _j, _len, _len1, _ref;
        if (width == null) {
          width = 30;
        }
        if (margin == null) {
          margin = 5;
        }
        if (!(attachment === 'bottom' || attachment === 'top' || attachment === 'left' || attachment === 'right')) {
          throw 'attachment must be either bottom, top, left or right';
        }
        columns = that.tableColumnsToObject(table);
        columnSums = sumColumns(columns);
        id = makeNewIds(table);
        classPart1 = attachment === 'bottom' || attachment === 'top' ? 'bar-horizontal' : 'bar-vertical';
        classPart2 = attachment;
        styleContainer = '';
        styleColumn = '';
        stylePart = '';
        if (attachment === 'left' || attachment === 'right') {
          styleContainer = "width: " + (Math.max.apply(0, columnSums)) + "px; height: " + (columns.head.length * (width + margin)) + "px";
          styleColumn1 = "height: " + width + "px; width:";
          styleColumn2 = "top:";
          stylePart = "position: relative; display:inline-block; height: " + width + "px; width:";
        } else {
          styleContainer = "height: " + (Math.max.apply(0, columnSums)) + "px; width: " + (columns.head.length * (width + margin)) + "px";
          styleColumn1 = "width: " + width + "px; height:";
          styleColumn2 = "left:";
          stylePart = "width: " + width + "px; height:";
        }
        chart = "<div id=\"" + id + "\" class=\"chart-" + classPart1 + "\" style=\"" + styleContainer + "\">";
        counter = 0;
        _ref = columns.values;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          subtable = _ref[_i];
          chart += "<div class=\"" + classPart1 + "\" style=\"" + styleColumn1 + " " + (columnSums[counter] + 10) + "px; " + styleColumn2 + " " + (counter * (width + margin)) + "px; " + attachment + ": 0px\">";
          level = 0;
          endLevel = attachment === 'bottom' || attachment === 'right' ? 0 : subtable.length - 1;
          for (_j = 0, _len1 = subtable.length; _j < _len1; _j++) {
            value = subtable[_j];
            levelAddition = '';
            if (level === endLevel) {
              levelAddition = '-head';
            }
            chart += "<div class=\"" + classPart1 + "-part-" + classPart2 + levelAddition + "\" style=\"" + stylePart + " " + value + "px\"><div class=\"text\">" + value + "</div></div>";
            level++;
          }
          chart += "</div>";
          counter++;
        }
        chart += "</div>";
        $(chart).insertAfter($("#" + table.id));
        $(table).addClass('hidden');
        return reboot.tables++;
      };
      $('table.htable-chart-bar-horizontal:not(.rebooted)').each(function() {
        return renderBarChart('bottom', this);
      });
      $('table.htable-chart-bar-horizontal-inversed:not(.rebooted)').each(function() {
        return renderBarChart('top', this);
      });
      $('table.htable-chart-bar-vertical:not(.rebooted)').each(function() {
        return renderBarChart('left', this);
      });
      return $('table.htable-chart-bar-vertical-inversed:not(.rebooted)').each(function() {
        return renderBarChart('right', this);
      });
    };

    return reboot;

  })();

  if (!(typeof $ !== "undefined" && $ !== null)) {
    throw 'jQuery needs to be installed and required in order to get reboot to run';
    console.error('reboot failed: jQuery not initialized');
  } else {
    $(document).ready(function() {
      var rebooter;
      rebooter = new reboot;
      try {
        return rebooter.rebootTableBarCharts();
      } catch (e) {
        return console.log(e);
      }
    });
  }

}).call(this);
