// Generated by CoffeeScript 1.3.3
(function() {
  var reboot, rebooter, root;

  root = typeof window !== "undefined" && window !== null ? window : global;

  reboot = (function() {

    function reboot() {
      if (!(typeof $ !== "undefined" && $ !== null)) {
        throw 'jQuery needs to be installed and required in order to get reboot to run';
        console.error('reboot failed: jQuery not initialized');
      }
      console.log('rebooted');
    }

    reboot.prototype.rebootTableBarCharts = function() {};

    return reboot;

  })();

  rebooter = new reboot;

}).call(this);
